name: fodome
description: A flutter app for donors to donate post about food or anything they have in excess and poeple who are in need can get access to it.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^7.0.1
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.3
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  uuid: ^4.5.1
  image: ^4.5.2
  animator: ^3.0.0
  path_provider: ^2.0.2
  firebase_messaging: ^15.2.3
  timeago: ^3.1.0
  cached_network_image: ^3.0.0
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.6
  settings_ui: ^2.0.2
  permission_handler: ^11.3.1
  android_intent: ^2.0.2
  google_maps_flutter: ^2.0.6
  overlay_support: ^2.1.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.6
  intl: ^0.19.0
  share: ^2.0.4
  http: ^1.3.0
  shimmer: ^3.0.0
  connectivity: ^3.0.6
  maps_launcher: ^3.0.0+1
  flutter_native_image: ^0.0.6
  flutter_email_sender: ^7.0.0
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.8.0
  bottom_navy_bar: ^6.0.0
  package_info_plus: ^8.2.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/custom_fodome_marker.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Spotify
      fonts:
        - asset: assets/fonts/Spotify/medium.ttf
        - asset: assets/fonts/Spotify/bold.otf
          weight: 700
        - asset: assets/fonts/Spotify/light.otf
          weight: 300
  assets:
    - assets/images/
    
